/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  volume?: number
  speed?: number
}
export function playFromBuf(buf: Buffer, opt?: Options | undefined | null): void
export function playFromSine(freq: number, ms: number, opt?: Options | undefined | null): void
