/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  volume?: number
  speed?: number
}
/**
 * The speed and volume is both set to 1.0 by default.
 * Note that calling this function blocks the main thread so use worker threads to make it non-blocking.
 */
export function playFromBuf(buf: Buffer, opt?: Options | undefined | null): void
/** Note that calling this function blocks the main thread so use worker threads to make it non-blocking. */
export function playFromSine(freq: number, ms: number, opt?: Options | undefined | null): void
